services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todoapp
    volumes:
      - ./postgres_data:/var/lib/postgresql/data