# Generated by Django 5.1.3 on 2024-12-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=512)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='core/fotos')),
                ('feito', models.BooleanField(default=False)),
            ],
        ),
    ]
